
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" onClick="window.location.reload()" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Ajouter une tache</h4>                
        </div>
        
        <div class="modal-body">                                     
            <form method="post" action="<?php echo $this->url('projet/edittache', array('action' => 'voirProjet', 'idprojet' => $projet->getId_projet(), 'actiontache' => 'edit-tache', 'idtache' => $tache->getId_tache(), true)); ?>" role="form" class="form-horizontal">                      
                <div class="form-group">
                    <label for="titre_tache" class="col-sm-2">Titre:</label>
                    <div class="col-sm-10"> 
                        <input type="text" name="titre_tache" value="<?php echo $tache->getTitre_tache(); ?>" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="descrition_tache" class="col-sm-2">Description:</label>
                    <div class="col-sm-10">
                        <textarea name="description_tache" class="form-control"><?php echo $tache->getDescription_tache(); ?></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label name="date_debut" class="col-sm-2">Début:</label>
                    <div class="col-sm-10">
                        <input type="date" name="date_debut" value="<?php echo $tache->getDate_debut()->format('d-m-Y H:m:s'); ?>" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="date_fin" class="col-sm-2">Fin:</label> 
                    <div class="col-sm-10">
                        <input type="date" name="date_fin" value="<?php echo $tache->getDate_fin()->format('d-m-Y H:m:s'); ?>" class="form-control">      
                    </div>
                </div>          
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="add tache"/>
                    <button type="button" class="btn btn-default" onClick="window.location.reload()" data-dismiss="modal">Close</button>                           
                </div>
            </form>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->