<div>
    <div>
        <div>
            <div>
                <h3>Liste de Projets</h3>
            </div>
            <div>
                <a data-toggle="modal" href="#addProjetModal" class="btn btn-primary btn-sm">Ajouter un projet</a>

                <?php if (isset($projets)) : ?>
                    <table>
                        <thead>
                            <tr>                        
                                <th>Titre</th>
                                <th>Description</th>
                                <th>Début</th>
                                <th>Fin</th>
                                <th>Status</th>
                                <th>Chef</th>
                                <th></th>
                            </tr>
                        </thead>
                        <?php foreach ($projets as $projet): ?>
                            <tbody>
                                <tr>                         
                                    <td><a href="<?php echo $this->url('projet', array('action' => 'voirProjet', 'idprojet' => $projet->getId_projet())); ?>"><?php echo $projet->getTitre_projet(); ?></a></td>
                                    <td><?php echo $projet->getDescription_projet(); ?></td>
                                    <td><?php echo $projet->getDate_debut_projet()->format('d-m-Y'); ?></td>
                                    <td><?php echo $projet->getDate_fin_projet()->format('d-m-Y'); ?></td>                                                                                    
                                    <td>
                                        <?php
                                        
                                        
                                            foreach ($status as $statu)
                                            {
                                                if ($projet->getId_status_projet() === $statu->getId_status_projet())
                                                {
                                                    $id_status = $projet->getId_status_projet();
                                                    $libelle = $statu->getLibelle_status_projet();
                                                    echo $libelle;
                                                }
                                            }
                                        
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        
                                        
                                            foreach ($users as $user)
                                            {
                                                if ($projet->getUser_id() === $user->getId())
                                                {
                                                    $id_user = $projet->getUser_id();
                                                    $display_name_user = $user->getDisplayName();
                                                    echo $display_name_user;
                                                }
                                            }
                                        
                                        ?>
                                    </td>
                                    
                                    <td>
                                        <a class="btn btn-primary" data-toggle="modal" href="<?php echo $this->url('projet', array('action' => 'editProjet', 'idprojet' => $projet->getId_projet())); ?>" data-target="#infos">Edit</a>|                        
                                        <a class="btn btn-primary" data-toggle="modal" href="<?php echo $this->url('projet', array('action' => 'deleteProjet', 'idprojet' => $projet->getId_projet())); ?>" data-target="#infos">Delete</a>                                                                
                                    </td>
                                </tr>
                            </tbody>
                        <?php endforeach; ?>
                    </table>                    
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>



<div class="modal " id="addProjetModal" tabindex="-1" role="dialog" aria-labelledby="addProjetModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Ajouter un projet</h4>
            </div>
            <div class="modal-body">
                <form name='addProjet' method="POST" action="<?php echo $this->url('projet', array('action' => 'addProjet', true)); ?>" role="form" class="form-horizontal">                                        
                        <div class="form-group">
                            <label for="titre_projet" class="col-sm-2">Titre: </label>                            
                            <div class="col-sm-10">
                                <input type="text" name="titre_projet" class="form-control" placeholder="Titre du projet...">
                            </div>                                                                
                        </div>                            
                        <div class="form-group">
                            <label for="description_projet" class="col-sm-2">Description:</label>
                            <div class="col-sm-10">                            
                            <textarea name="description_projet"  class="form-control" rows="2" placeholder="Courte description du projet..."></textarea>
                            </div>                 
                        </div>
                        <div class="form-group">
                            <label for="date_debut_projet" class="col-sm-2">Début:</label>                                     
                            <div class="col-sm-10">
                            <input type="date" name="date_debut_projet" class="form-control">
                            </div>                 
                        </div>
                        <div class="form-group">
                            <label for="date_fin_projet"class="col-sm-2">Fin:</label>      
                            <div class="col-sm-10">
                            <input type="date" name="date_fin_projet" class="form-control">
                            </div>                                         
                        </div>
                        <div class="modal-footer">
                            <input type="submit" class="btn btn-primary" value="Valider"/>
                            
                            <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>

                        </div>                    
                </form>

            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div id="infos" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" onClick="window.location.reload()" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Chargement...</h4>                
            </div>
            <div class="modal-body">
                <style>
                    #followingBallsG{
                        position:relative;
                        width:256px;
                        height:20px;
                    }

                    .followingBallsG{
                        background-color:#29BCCF;
                        position:absolute;
                        top:0;
                        left:0;
                        width:20px;
                        height:20px;
                        -moz-border-radius:10px;
                        -moz-animation-name:bounce_followingBallsG;
                        -moz-animation-duration:2.6s;
                        -moz-animation-iteration-count:infinite;
                        -moz-animation-direction:linear;
                        -webkit-border-radius:10px;
                        -webkit-animation-name:bounce_followingBallsG;
                        -webkit-animation-duration:2.6s;
                        -webkit-animation-iteration-count:infinite;
                        -webkit-animation-direction:linear;
                        -ms-border-radius:10px;
                        -ms-animation-name:bounce_followingBallsG;
                        -ms-animation-duration:2.6s;
                        -ms-animation-iteration-count:infinite;
                        -ms-animation-direction:linear;
                        -o-border-radius:10px;
                        -o-animation-name:bounce_followingBallsG;
                        -o-animation-duration:2.6s;
                        -o-animation-iteration-count:infinite;
                        -o-animation-direction:linear;
                        border-radius:10px;
                        animation-name:bounce_followingBallsG;
                        animation-duration:2.6s;
                        animation-iteration-count:infinite;
                        animation-direction:linear;
                    }

                    #followingBallsG_1{
                        -moz-animation-delay:0s;
                    }

                    #followingBallsG_1{
                        -webkit-animation-delay:0s;
                    }

                    #followingBallsG_1{
                        -ms-animation-delay:0s;
                    }

                    #followingBallsG_1{
                        -o-animation-delay:0s;
                    }

                    #followingBallsG_1{
                        animation-delay:0s;
                    }

                    #followingBallsG_2{
                        -moz-animation-delay:0.26s;
                        -webkit-animation-delay:0.26s;
                        -ms-animation-delay:0.26s;
                        -o-animation-delay:0.26s;
                        animation-delay:0.26s;
                    }

                    #followingBallsG_3{
                        -moz-animation-delay:0.52s;
                        -webkit-animation-delay:0.52s;
                        -ms-animation-delay:0.52s;
                        -o-animation-delay:0.52s;
                        animation-delay:0.52s;
                    }

                    #followingBallsG_4{
                        -moz-animation-delay:0.78s;
                        -webkit-animation-delay:0.78s;
                        -ms-animation-delay:0.78s;
                        -o-animation-delay:0.78s;
                        animation-delay:0.78s;
                    }

                    @-moz-keyframes bounce_followingBallsG{
                        0%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    50%{
                        left:236px;
                        background-color:#FFFFFF;
                    }

                    100%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    }

                    @-webkit-keyframes bounce_followingBallsG{
                        0%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    50%{
                        left:236px;
                        background-color:#FFFFFF;
                    }

                    100%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    }

                    @-ms-keyframes bounce_followingBallsG{
                        0%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    50%{
                        left:236px;
                        background-color:#FFFFFF;
                    }

                    100%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    }

                    @-o-keyframes bounce_followingBallsG{
                        0%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    50%{
                        left:236px;
                        background-color:#FFFFFF;
                    }

                    100%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    }

                    @keyframes bounce_followingBallsG{
                        0%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    50%{
                        left:236px;
                        background-color:#FFFFFF;
                    }

                    100%{
                        left:0px;
                        background-color:#29BCCF;
                    }

                    }

                </style>
                <div id="followingBallsG">
                    <div id="followingBallsG_1" class="followingBallsG">
                    </div>
                    <div id="followingBallsG_2" class="followingBallsG">
                    </div>
                    <div id="followingBallsG_3" class="followingBallsG">
                    </div>
                    <div id="followingBallsG_4" class="followingBallsG">
                    </div>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>


  
<div class="container">
    <div class="col-md-10">
        <div class='well'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker5'>
                    <input type='text' class="form-control" data-format="YYYY/MM/DD" />
                    <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker5').datetimepicker({
                    pickTime: false
                });
            });
        </script>
    </div>
</div>